### ISSUE TITLE
2.10.0 Outpost error and bug on cp/licensing 

### ISSUE THREAD

**Issue by Bferreira5** [jrc9designstudio/google-analytics-v2-hub#2]
Within the CP, looks like 2.10.0 introduced a bunch of changes to how licensing works. Clicking the manage licence tab or button to for to` cp/licensing`

**Seeing a few ErrorExceptions like:**
```
ErrorException in License.php line 28: Call to undefined method Statamic\Addons\GoogleAnalytics\GoogleAnalyticsAPI::name() (View: /Users/benjaminferreira/Code/app/studioworthy/statamic/resources/views/licensing/index.blade.php)
```
```
FatalThrowableError in License.php line 28: Call to undefined method Statamic\Addons\GoogleAnalytics\GoogleAnalyticsAPI::name()
```

**I double checked if the correct license is present.** 

Attached stack trace relevent
[log.txt](https://github.com/jrc9designstudio/google-analytics-v2-hub/files/2206305/log.txt)

Tested on Valet DEV env, but likely occurring in Prod.

**Comment by jasonvarga** [comment]
This one is on us in the core. 

~We'll sort it out for 2.10.1~ It's been added to 2.10.1, ~which will be released soon.~ which has been released.

**Comment by jcohlmeyer** [comment]
Thank you for fixing this so fast in core Jason!
