### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by chrisburton** [jrc9designstudio/google-analytics-v2-hub#3]
In `google-analytics/settings`, there's a typo.

**Typo:** "Trafic"

<img src="https://dzwonsemrish7.cloudfront.net/items/1S1c1B3g3U3G363g0A1E/Screen%20Shot%202018-07-22%20at%205.54.42%20PM.jpg">

**Comment by jcohlmeyer** [comment]
Fixed in [2.2.1](https://github.com/jcohlmeyer/statamic-google-analytics/releases/tag/2.2.1)
