### ISSUE TITLE
Display issue?

### ISSUE THREAD

**Issue by chrisburton** [jrc9designstudio/google-analytics-v2-hub#5]
Version: **`2.10.2`**

Upon installing, I placed my tracking code in the settings page and placed the tag in my head section. Then I sent some test traffic but I'm not seeing any results. Am I doing something wrong? 

It also seems like the display cards have css issues?

<img src="https://dzwonsemrish7.cloudfront.net/items/2a350R2W3H300Z0Y2h2V/Screen%20Shot%202018-07-22%20at%206.17.44%20PM.jpg">

Maybe related to the console error I'm getting?

```js
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.length')
```

**Comment by jcohlmeyer** [comment]
@chrisburton to see the reports you need to set up the Google Analytics Reporting API as documented here: https://statamic.com/marketplace/addons/google-analytics/docs#reporting-setup

Please note that if this is a new Google Analytics account it may take some tome (24-48 hours I think) for there to be any results reported.
